package com.school_management_webapi.entity;

/** What an audit entry records. The web app words each one for the log. */
public enum AuditAction {
	SIGNED_IN,
	SIGN_IN_FAILED,
	SIGNED_OUT,
	PASSWORD_RESET,
	SESSION_REVOKED,
	USER_INVITED,
	USER_UPDATED,
	USER_REMOVED,
	ROLE_CREATED,
	ROLE_UPDATED,
	ROLE_DELETED,
	SECURITY_SETTINGS_CHANGED,
	ACADEMIC_SETTINGS_CHANGED,
	SYSTEM_SETTINGS_CHANGED,
	MAINTENANCE_MODE_CHANGED,
	DATA_EXPORTED,
	DATA_DELETED,
	PLAN_CHANGED,
	PLAN_CANCELED,
	TWO_FACTOR_ENABLED,
	TWO_FACTOR_DISABLED,
	TWO_FACTOR_RESET,
	RECOVERY_CODES_REGENERATED
}
